# Generated by Django 6.0 on 2026-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_asset_delete_manageduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('Equity', 'Equity'), ('Debt', 'Debt'), ('Crypto', 'Crypto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
