# Generated by Django 6.0 on 2026-01-02 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_asset_asset_class_alter_asset_risk_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='return_percent',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('Equity', 'Equity'), ('Equipment', 'Equipment'), ('Vehicle', 'Vehicle')], max_length=20),
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='damage_images/')),
                ('damage_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asset')),
            ],
        ),
    ]
