# Generated by Django 6.0 on 2026-01-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='damagereport',
            name='asset',
        ),
        migrations.DeleteModel(
            name='PendingTask',
        ),
        migrations.RemoveField(
            model_name='systemactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='DamageReport',
        ),
        migrations.DeleteModel(
            name='SystemActivity',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
