# Generated by Django 6.0 on 2026-01-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_missing_user_fields'),
        ('api', '0010_add_missing_user_fields'),
    ]

    operations = [
    ]
